### ISSUE TITLE
cannot load nif decoder

### ISSUE THREAD

**Issue by codenoid** [membraneframework/membrane-demo#4]
Environment : 
```
Ubuntu 16.04
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

Error log : 

```
iex(1)> alias Membrane.Demo.MP3.Pipeline              
Membrane.Demo.MP3.Pipeline
iex(2)> {:ok, pid} = Pipeline.start_link("sample.mp3")
{:ok, #PID<0.384.0>}
iex(3)> Pipeline.play(pid)                            
:ok     
iex(4)> 
20:42:29.768 [error] Process #PID<0.392.0> raised an exception
** (RuntimeError) Bundlex cannot load nif "decoder" of app :membrane_element_mad
from "/var/app/elixir/learn-membraneframework/membrane-demo/_build/dev/lib/membrane_element_mad/priv/bundlex/decoder", check bundlex.exs file for information about nifs.
Reason: :load_failed, Failed to load NIF library: '/var/app/elixir/learn-membraneframework/membrane-demo/_build/dev/lib/membrane_element_mad/priv/bundlex/decoder.so: undefined symbol: mad_stream_buffer'

    (membrane_element_mad) lib/membrane_element_mad/decoder_native.ex:1: Membrane.Element.Mad.Decoder.Native.Nif.load_nif/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
 
20:42:29.769 [error] Process #PID<0.393.0> raised an exception
** (RuntimeError) Bundlex cannot load nif "sink" of app :membrane_element_portaudio
from "/var/app/elixir/learn-membraneframework/membrane-demo/_build/dev/lib/membrane_element_portaudio/priv/bundlex/sink", check bundlex.exs file for information about nifs.
Reason: :load_failed, Failed to load NIF library: '/var/app/elixir/learn-membraneframework/membrane-demo/_build/dev/lib/membrane_element_portaudio/priv/bundlex/sink.so: undefined symbol: Pa_Terminate'

    (membrane_element_portaudio) lib/membrane_element_portaudio/sink_native.ex:1: Membrane.Element.PortAudio.Sink.Native.Nif.load_nif/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
2019-06-20T13:42:29.769926Z [warn] [decoder core] Encountered an error.

```

**Comment by bblaszkow06** [comment]
Hi @codenoid, thanks for reporting! It seems that readme for demo misses the info about required native dependencies. Can you try installing them and then try running the demo again? The instructions can be found in our guide (https://www.membraneframework.org/guide/v0.3/pipeline.html#ubuntu)

**Comment by codenoid** [comment]
hi @bblaszkow06 i already install that (and error)

**Comment by bblaszkow06** [comment]
OK, please try the following: 
```bash
rm -rf _build
mix deps.update --all
mix compile
```
and then running `iex -S mix` and the demo again

**Comment by codenoid** [comment]
thankyou ! that solve the issue

```
iex(6)> ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
                                                                              ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
                                                                                                                                                          ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side                                                                                      ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
                  ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
                                                                                              ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map                       
 ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map                                                                                           shm_open() failed: No such file or directory
        ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
shm_open() failed: No such file or directory
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error                                                                                      shm_open() failed: No such file or directory                                                                                                                                      ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
shm_open() failed: No such file or directory
 ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
{:start_of_stream, :input}
```

i don't know but i was having a problem with ALSA, maybe i'll try on different device
